GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/artist
###
POST http://localhost:3000/songs/add
Content-Type: application/json

{
    "title": "title", 
    "artist": "artist",
    "album": "album", 
    "year": "year"
}
###
DELETE http://localhost:3000/songs/delete/id